name: Update proxies.txt

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download proxies.txt from Gist
        run: |
          curl -L --fail \
            "https://raw.githubusercontent.com/SlavaKat/ProxyNova-/refs/heads/main/ProxyNova%20%E2%9D%AF%20%D0%A0%D0%B5%D0%B7%D0%B5%D1%80%D0%B2%20%E2%9D%AF%20%D0%A0%D1%83%D1%87%D0%BD%D0%BE%D0%B9%20%D0%B2%D1%8B%D0%B1%D0%BE%D1%80.txt" \
            -o proxies.txt

      - name: Check and commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet -- proxies.txt; then
            echo "proxies.txt has not changed"
          else
            git add proxies.txt
            git commit -m "Update proxies.txt"
            git push
          fi
